
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthContextWrapper } from "@/contexts/authContext";
import { GameContextWrapper } from "@/contexts/gameContext";
import Provider from "@/utils/Provider";
import { StreakGameContextWrapper } from "@/contexts/streakGameContext";
import ErrorBoundary from "@/components/errorBoundary/ErrorBoundary";

// Define custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "REALorNOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased remove-selecting-text">
        <AuthContextWrapper>
          <GameContextWrapper>
            <StreakGameContextWrapper>
              <Provider>{children}</Provider>
            </StreakGameContextWrapper>
          </GameContextWrapper>
        </AuthContextWrapper>
      </body>
    </html>
  );
}











