import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthContextWrapper } from "@/contexts/authContext";
import { GameContextWrapper } from "@/contexts/gameContext";
import Provider from "@/utils/Provider";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClient = new QueryClient();
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextWrapper>
      <GameContextWrapper>

        <QueryClientProvider client={queryClient}>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Provider>{children}</Provider>
            </body>
          </html>

        </QueryClientProvider>

      </GameContextWrapper>
    </AuthContextWrapper>
  );
}
