//export const metadata = {
//  title: 'Next.js',
// description: 'Generated by Next.js',
///}

//export default function RootLayout({
//  children,
//}: {
// children: React.ReactNode
///}) {
//return (
//<html lang="en">
//  <body>{children}</body>
//  </html>
// )
//}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (

    <div >{children}</div>
  );
}
